[package]
name = "dbdrill"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
cursive = "0.21.1"
postgres = "0.19.10"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"
